name: cmake

on:
  push:
  pull_request:

jobs:
  build_windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        target: [gcc-shared, gcc-static, clang-shared, clang-static]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: |
        SYSTEMC_CI_TARGET=${{ matrix.target }} SYSTEMC_SRC_PATH=$PWD docker/entrypoint.sh
