name: cmake

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        version: [20.04, 22.04]
        platform: [linux/arm64]
        target: [gcc-shared]
    steps:
    - name: Install docker
      run: |
        brew install docker
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: |
        docker buildx build --platform ${{ matrix.platform }} -t systemc_test --build-arg UBUNTU_VERSION=${{ matrix.version }} -f docker/ubuntu.dockerfile .
        docker run -e SYSTEMC_CI_TARGET=${{ matrix.target }} systemc_test
