name: cmake

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        target: [gcc-shared]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: |
        SYSTEMC_CI_TARGET=${{ matrix.target }} /docker/entrypoint.sh
