name: cmake

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        version: [20.04]
        platform: [linux/arm64]
        target: [gcc-shared]
    steps:
    - name: Install docker
      run: |
        HOMEBREW_NO_AUTO_UPDATE=1 brew install --cask docker
        sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended --install-privileged-components
        open -a /Applications/Docker.app --args --unattended --accept-license
        echo "We are waiting for Docker to be up and running. It can take over 2 minutes..."
        while ! /Applications/Docker.app/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done
        docker version
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: |
        docker build --platform ${{ matrix.platform }} -t systemc_test --build-arg UBUNTU_VERSION=${{ matrix.version }} -f docker/ubuntu.dockerfile .
        docker run -e SYSTEMC_CI_TARGET=${{ matrix.target }} systemc_test
