name: regression

on:
  push:
  pull_request:

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      run: |
        cmake -B BUILD/RELEASE/BUILD -DENABLE_REGRESSION=true .
        cmake --build BUILD/RELEASE/BUILD --config RELEASE --parallel
        make -C BUILD/RELEASE/BUILD/ check
